export const blogPosts = [
  {
    id: '1',
    title: 'CoachBot - A GPT on Steroids to Support Your Goal Achievement and Personal Growth',
    metaTitle: 'CoachBot - AI-Powered Coaching for Personal and Career Growth',
    description:
      'Discover CoachBot, an AI-powered coaching tool that adapts to your goals, helping you achieve personal and career growth. With 24/7 support, accountability, and actionable insights to boost confidence and reach new milestones',
    imageUrl: 'post-1/1.jpg',
    postingDate: '11/22/2024',
    readingTime: 234234,
    contentUrl: 'post-1/1.md',
    categoryName: 'Personal Growth',
  },
  {
    id: '2',
    title: 'TIPS For on Goal Setting for Young Professionals',
    metaTitle: 'Achieve Your Personal Goals with AI: How CoachBot Supports Junior Professionals',
    description:
      'Explore how CoachBot, an AI-powered coach, helps young professionals set, track, and achieve personal goals with guidance and accountability. Try CoachBot for personalized support and hybrid coaching options.',
    imageUrl: 'post-2/2.jpg',
    postingDate: '11/19/2024',
    readingTime: 234234,
    contentUrl: 'post-2/2.md',
    categoryName: 'Personal Growth',
  },
  {
    id: '3',
    title: '10 Ways You can Build Self-Confidence in the Workplace from CoachBot',
    metaTitle: 'Boost Your Workplace Confidence with AI Coaching: 10 Tips with CoachBot',
    description:
      'Learn how CoachBot’s AI-powered coaching can help you build self-confidence in the workplace. Discover ways to improve your self-esteem, overcome doubts, and achieve career success.',
    imageUrl: 'post-3/3.jpg',
    postingDate: '11/15/2024',
    readingTime: 234234,
    contentUrl: 'post-3/3.md',
    categoryName: 'Business & Career',
  },
  {
    id: '4',
    title: 'Achieving Work-Life Balance with AI Coaching as a Junior Professiona',
    metaTitle: 'Work-Life Balance for Junior Professionals: Find Harmony with AI Coaching',
    description:
      'Discover how CoachBot’s AI-powered coaching helps junior professionals achieve work-life balance and reduce burnout. Set boundaries, prioritize well-being, and thrive in your career with CoachBot.',
    imageUrl: 'post-4/4.jpg',
    postingDate: '11/12/2024',
    readingTime: 234234,
    contentUrl: 'post-4/4.md',
    categoryName: 'Health & Wellbeing',
  },
  {
    id: '5',
    title: 'Top Myths About AI Coaching (And Why They’re Wrong)',
    metaTitle:
      'Top Myths About AI Coaching Debunked: Discover CoachBot’s Secure, Empathetic, and Accessible AI Support',
    description:
      'Think AI coaching lacks empathy or security? Discover how CoachBot combines advanced AI with expert human coaching, secure WhatsApp access, and personalized growth support.',
    imageUrl: 'post-5/5.jpg',
    postingDate: '11/09/2024',
    readingTime: 234234,
    contentUrl: 'post-5/5.md',
    categoryName: '',
  },
  {
    id: '6',
    title: 'Why You Don’t Need to Be a CEO to Benefit from Coaching',
    metaTitle: 'Coaching for Everyone: How CoachBot Supports Growth for All Professionals',
    description:
      'Discover how coaching through CoachBot is for everyone—not just CEOs. Available on WhatsApp, CoachBot offers AI and human coaching for career, personal growth, and life vision.',
    imageUrl: 'post-6/6.jpg',
    postingDate: '11/05/2024',
    readingTime: 234234,
    contentUrl: 'post-6/6.md',
    categoryName: '',
  },
  {
    id: '7',
    title: 'Mastering the Wheel of Emotions for Self-Awareness and Growth',
    metaTitle: 'Understanding Emotions: A Guide to Better Self-Awareness and Growth',
    description:
      'Learn to master your emotions through the Wheel of Emotions framework. Discover practical techniques for emotional awareness, understanding triggers, and developing stronger relationships in both personal and professional contexts.',
    imageUrl: 'post-7/7.jpg',
    postingDate: '12/30/2024',
    readingTime: 360000,
    contentUrl: 'post-7/7.md',
    categoryName: 'Managing mental health and well-being',
  },
  {
    id: '8',
    title: 'CBT Techniques: Breaking Free from Negative Thought Patterns',
    metaTitle: 'Achieve Your Personal Goals with AI: How CoachBot Supports Junior Professionals',
    description:
      'Transform your mindset with evidence-based CBT techniques. Learn to identify cognitive distortions, break negative thought patterns, and build resilience for better mental health and professional success.',
    imageUrl: 'post-8/8.jpg',
    postingDate: '12/30/2024',
    readingTime: 480000,
    contentUrl: 'post-8/8.md',
    categoryName: 'Managing stress and anxiety',
  },
  {
    id: '9',
    title: '90-Day Action Plan: Templates for Crushing Goals with CoachBot',
    metaTitle: 'Boost Your Workplace Confidence with AI Coaching: 10 Tips with CoachBot',
    description:
      'A comprehensive guide to creating and executing an effective 90-day action plan using CoachBot. Learn to set achievable goals, track progress, and maintain momentum for sustainable personal growth.',
    imageUrl: 'post-9/9.jpg',
    postingDate: '12/30/2024',
    readingTime: 300000,
    contentUrl: 'post-9/9.md',
    categoryName: 'Setting and achieving personal goals',
  },
  {
    id: '10',
    title: 'The Prioritization Matrix: Achieve More by Doing Less',
    metaTitle: 'Master Your Time: Using the Eisenhower Matrix for Better Productivity',
    description:
      'Master the art of prioritization with the Eisenhower Matrix. Learn practical strategies for time management, task organization, and achieving more by focusing on what truly matters.',
    imageUrl: 'post-10/10.jpg',
    postingDate: '12/30/2024',
    readingTime: 420000,
    contentUrl: 'post-10/10.md',
    categoryName: 'Creating a productive and inspiring workspace',
  },
  {
    id: '11',
    title: 'Why Emotional Intelligence Is the New Professional Superpower',
    metaTitle:
      'EQ at Work: Leveraging Emotional Intelligence for Career Success',
    description:
      'Discover why emotional intelligence is crucial for professional success. Learn key EQ skills including self-awareness, empathy, and social management to enhance your leadership potential and career growth.',
    imageUrl: 'post-11/11.jpg',
    postingDate: '12/30/2024',
    readingTime: 300000,
    contentUrl: 'post-11/11.md',
    categoryName: 'Building a professional network',
  },
  {
    id: '12',
    title: 'The Hidden Science Behind Motivation: How to Stay Consistently Inspired',
    metaTitle: 'Understanding Motivation: The Science of Staying Inspired',
    description:
      'Understand the science behind motivation and learn practical strategies to stay consistently inspired. Explore both intrinsic and extrinsic motivators while developing sustainable habits for long-term success.',
    imageUrl: 'post-12/12.jpg',
    postingDate: '12/30/2024',
    readingTime: 240000,
    contentUrl: 'post-12/12.md',
    categoryName: 'Finding motivation and overcoming procrastination',
  },
  {
    id: '13',
    title: 'How to Build Your First AI Coach (Without Writing a Line of Code)',
    metaTitle: 'From idea to impact the practical roadmap for turning your IP into an AI-powered experience.',
    description:
      'Let’s be honest for a moment. Most coaches didn’t become coaches to learn how to code.',
    imageUrl: 'post-13/13.jpg',
    postingDate: '11/27/2025',
    readingTime: 240000,
    contentUrl: 'post-13/13.md',
    categoryName: 'Creating a productive and inspiring workspace',
  },
  {
  id: '14',
  title: 'CoachBot AI Launches Responsible AI & Coaching Quality Council to Shape the Future of Human-Centered Coaching',
  metaTitle: 'Coaching Quality Council to Shape the Future of Human-Centered Coaching',
  description: 'Berlin, Germany, November 2025. CoachBot AI, a pioneer in the space of conversational AI for learning and development',
  imageUrl: 'post-14/14.jpg',
  postingDate: '12/18/2025',
  readingTime: 300000,
  contentUrl: 'post-14/14.md',
  categoryName: 'Creating a productive and inspiring workspace',
  author: 'Coachbot AI',
}
];
