export const categories = [
  {
    id: 'health-wellbeing-z8x7y6v3',
    name: 'Health & Wellbeing',
    instruction: 'Focusing on physical and mental health improvement',
    image: '',
    translateKey: 'Categories.options.healthAndWellbeing.name',
    tooltipKey: 'Categories.options.healthAndWellbeing.description',
    order: 1,
    subcategories: [
      {
        id: 'health-wellbeing-z8x7y6v3-healthy-diet-a9b8c7d6',
        name: 'Establishing and maintaining a healthy diet',
        instruction: 'Guidance on developing and sticking to nutritious eating habits',
        image: '',
        translateKey: 'Categories.options.healthAndWellbeing.establishingAndMaintainingAHealthyDiet',
      },
      {
        id: 'health-wellbeing-z8x7y6v3-exercise-routine-e5f4g3h2',
        name: 'Creating and sticking to an exercise routine',
        instruction: 'Strategies for developing and maintaining a regular fitness regimen',
        image: '',
        translateKey: 'Categories.options.healthAndWellbeing.creatingAndStickingToAnExerciseRoutine',
      },
      {
        id: 'health-wellbeing-z8x7y6v3-mental-health-i1j2k3l4',
        name: 'Managing mental health and well-being',
        instruction: 'Techniques for maintaining good mental health and emotional balance',
        image: '',
        translateKey: 'Categories.options.healthAndWellbeing.managingMentalHealthAndWellbeing',
      },
      {
        id: 'health-wellbeing-z8x7y6v3-sleep-routine-m5n6o7p8',
        name: 'Balancing sleep and daily routines',
        instruction: 'Methods for optimizing sleep patterns and daily schedules for overall well-being',
        image: '',
        translateKey: 'Categories.options.healthAndWellbeing.balancingSleepAndDailyRoutines',
      },
    ],
  },
  {
    id: 'finances-q9r8s7t6',
    name: 'Finances',
    instruction: 'Managing personal finances, budgeting, and financial planning',
    image: '',
    translateKey: 'Categories.options.finances.name',
    tooltipKey: 'Categories.options.finances.description',
    order: 2,
    subcategories: [
      {
        id: 'finances-q9r8s7t6-manage-loan-debt-u5v4w3x2',
        name: 'Managing loan debt',
        instruction: 'Strategies for effectively managing and repaying loan debt',
        image: '',
        translateKey: 'Categories.options.finances.managingLoanDebt',
      },
      {
        id: 'finances-q9r8s7t6-budget-y1z2a3b4',
        name: 'Creating and sticking to a budget',
        instruction: 'Techniques for creating a realistic budget and maintaining financial discipline',
        image: '',
        translateKey: 'Categories.options.finances.creatingAndStickingToABudget',
      },
      {
        id: 'finances-q9r8s7t6-savings-c5d6e7f8',
        name: 'Saving for major life events',
        instruction: 'Planning and saving strategies for significant expenses like buying a house or starting a family',
        image: '',
        translateKey: 'Categories.options.finances.savingForMajorLifeEvents',
      },
      {
        id: 'finances-q9r8s7t6-income-sources-g9h8i7j6',
        name: 'Finding other sources of income',
        instruction: 'Exploring opportunities for additional income streams and side hustles',
        image: '',
        translateKey: 'Categories.options.finances.findingOtherSourcesOfIncome',
      },
    ],
  },
  {
    id: 'family-and-friends-k1l2m3n4',
    name: 'Family & Friends',
    instruction: 'Nurturing relationships with family and friends',
    image: '',
    translateKey: 'Categories.options.familyAndFriends.name',
    tooltipKey: 'Categories.options.familyAndFriends.description',
    order: 3,
    subcategories: [
      {
        id: 'family-and-friends-k1l2m3n4-family-obligations-o5p6q7r8',
        name: 'Navigating family expectations and obligations',
        instruction: 'Strategies for managing family responsibilities while maintaining personal boundaries',
        image: '',
        translateKey: 'Categories.options.familyAndFriends.navigatingFamilyExpectationsAndObligations',
      },
      {
        id: 'family-and-friends-k1l2m3n4-work-social-balance-s9t8u7v6',
        name: 'Balancing time between work and social life',
        instruction: 'Techniques for maintaining a healthy work-life balance and nurturing social connections',
        image: '',
        translateKey: 'Categories.options.familyAndFriends.balancingTimeBetweenWorkAndSocialLife',
      },
      {
        id: 'family-and-friends-k1l2m3n4-communication-w1x2y3z4',
        name: 'Improving communication skills with family and friends',
        instruction: 'Enhancing interpersonal communication for stronger relationships',
        image: '',
        translateKey: 'Categories.options.familyAndFriends.improvingCommunicationSkillsWithFamilyAndFriends',
      },
      {
        id: 'family-and-friends-k1l2m3n4-friendships-a5b6c7d8',
        name: 'Building and maintaining meaningful friendships',
        instruction: 'Strategies for cultivating deep and lasting friendships',
        image: '',
        translateKey: 'Categories.options.familyAndFriends.buildingAndMaintainingMeaningfulFriendships',
      },
    ],
  },
  {
    id: 'romance-e9f8g7h6',
    name: 'Romance',
    instruction: 'Navigating romantic relationships and personal connections',
    image: '',
    translateKey: 'Categories.options.romance.name',
    tooltipKey: 'Categories.options.romance.description',
    order: 4,
    subcategories: [
      {
        id: 'romance-e9f8g7h6-finding-partner-i1j2k3l4',
        name: 'Finding a compatible partner',
        instruction: 'Guidance on identifying and connecting with potential romantic partners',
        image: '',
        translateKey: 'Categories.options.romance.findingACompatiblePartner',
      },
      {
        id: 'romance-e9f8g7h6-relationship-balance-m5n6o7p8',
        name: 'Maintaining a healthy work-life balance in relationships',
        instruction: 'Strategies for balancing career demands with romantic commitments',
        image: '',
        translateKey: 'Categories.options.romance.maintainingAHealthyWorkLifeBalanceInRelationships',
      },
      {
        id: 'romance-e9f8g7h6-partner-communication-q9r8s7t6',
        name: 'Communicating effectively with a partner',
        instruction: 'Techniques for clear and empathetic communication in romantic relationships',
        image: '',
        translateKey: 'Categories.options.romance.communicatingEffectivelyWithAPartner',
      },
      {
        id: 'romance-e9f8g7h6-trust-intimacy-u5v4w3x2',
        name: 'Overcoming trust issues and building intimacy',
        instruction: 'Methods for addressing trust concerns and deepening emotional connections',
        image: '',
        translateKey: 'Categories.options.romance.overcomingTrustIssuesAndBuildingIntimacy',
      },
    ],
  },
  {
    id: 'personal-growth-y1z2a3b4',
    name: 'Personal Growth',
    instruction: 'Focusing on self-improvement and personal development',
    image: '',
    translateKey: 'Categories.options.personalGrowth.name',
    tooltipKey: 'Categories.options.personalGrowth.description',
    order: 5,
    subcategories: [
      {
        id: 'personal-growth-y1z2a3b4-goal-setting-c5d6e7f8',
        name: 'Setting and achieving personal goals',
        instruction: 'Techniques for effective goal-setting and achievement strategies',
        image: '',
        translateKey: 'Categories.options.personalGrowth.settingAndAchievingPersonalGoals',
      },
      {
        id: 'personal-growth-y1z2a3b4-self-confidence-g9h8i7j6',
        name: 'Building self-confidence and self-esteem',
        instruction: 'Methods for improving self-image and boosting confidence',
        image: '',
        translateKey: 'Categories.options.personalGrowth.buildingSelfConfidenceAndSelfEsteem',
      },
      {
        id: 'personal-growth-y1z2a3b4-stress-anxiety-k1l2m3n4',
        name: 'Managing stress and anxiety',
        instruction: 'Strategies for coping with and reducing stress and anxiety',
        image: '',
        translateKey: 'Categories.options.personalGrowth.managingStressAndAnxiety',
      },
      {
        id: 'personal-growth-y1z2a3b4-motivation-procrastination-o5p6q7r8',
        name: 'Finding motivation and overcoming procrastination',
        instruction: 'Techniques for increasing productivity and combating procrastination',
        image: '',
        translateKey: 'Categories.options.personalGrowth.findingMotivationAndOvercomingProcrastination',
      },
    ],
  },
  {
    id: 'fun-and-recreation-s9t8u7v6',
    name: 'Fun & Recreation',
    instruction: 'Balancing enjoyment and leisure activities with daily responsibilities',
    image: '',
    translateKey: 'Categories.options.funAndRecreation.name',
    tooltipKey: 'Categories.options.funAndRecreation.description',
    order: 6,
    subcategories: [
      {
        id: 'fun-and-recreation-s9t8u7v6-hobbies-w1x2y3z4',
        name: 'Discovering new hobbies and interests',
        instruction: 'Guidance on exploring and developing new recreational pursuits',
        image: '',
        translateKey: 'Categories.options.funAndRecreation.discoveringNewHobbiesAndInterests',
      },
      {
        id: 'fun-and-recreation-s9t8u7v6-leisure-responsibilities-a5b6c7d8',
        name: 'Balancing leisure activities with responsibilities',
        instruction: 'Strategies for incorporating fun into a busy lifestyle',
        image: '',
        translateKey: 'Categories.options.funAndRecreation.balancingLeisureActivitiesWithResponsibilities',
      },
      {
        id: 'fun-and-recreation-s9t8u7v6-vacations-trips-e9f8g7h6',
        name: 'Planning and enjoying vacations and trips',
        instruction: 'Tips for organizing and maximizing enjoyment of travel experiences',
        image: '',
        translateKey: 'Categories.options.funAndRecreation.planningAndEnjoyingVacationsAndTrips',
      },
      {
        id: 'fun-and-recreation-s9t8u7v6-social-life-i1j2k3l4',
        name: 'Building a social life that includes fun and recreation',
        instruction: 'Methods for integrating enjoyable activities into your social circle',
        image: '',
        translateKey: 'Categories.options.funAndRecreation.buildingASocialLifeThatIncludesFunAndRecreation',
      },
    ],
  },
  {
    id: 'business-and-career-m5n6o7p8',
    name: 'Business & Career',
    instruction: 'Focusing on professional development and career advancement',
    image: '',
    translateKey: 'Categories.options.businessAndCareer.name',
    tooltipKey: 'Categories.options.businessAndCareer.description',
    order: 7,
    subcategories: [
      {
        id: 'business-and-career-m5n6o7p8-career-path-q9r8s7t6',
        name: 'Finding the right career path',
        instruction: 'Guidance on identifying and pursuing suitable career options',
        image: '',
        translateKey: 'Categories.options.businessAndCareer.findingTheRightCareerPath',
      },
      {
        id: 'business-and-career-m5n6o7p8-career-transitions-u5v4w3x2',
        name: 'Navigating career transitions and job changes',
        instruction: 'Strategies for managing professional shifts and new job opportunities',
        image: '',
        translateKey: 'Categories.options.businessAndCareer.navigatingCareerTransitionsAndJobChanges',
      },
      {
        id: 'business-and-career-m5n6o7p8-professional-network-y1z2a3b4',
        name: 'Building a professional network',
        instruction: 'Techniques for expanding and maintaining valuable professional connections',
        image: '',
        translateKey: 'Categories.options.businessAndCareer.buildingAProfessionalNetwork',
      },
      {
        id: 'business-and-career-m5n6o7p8-skills-development-c5d6e7f8',
        name: 'Enhancing skills and professional development',
        instruction: 'Methods for continuous learning and skill improvement in your career',
        image: '',
        translateKey: 'Categories.options.businessAndCareer.enhancingSkillsAndProfessionalDevelopment',
      },
    ],
  },
  {
    id: 'physical-environment-g9h8i7j6',
    name: 'Physical Environment',
    instruction: 'Creating and maintaining optimal living and working spaces',
    image: '',
    translateKey: 'Categories.options.physicalEnvironment.name',
    tooltipKey: 'Categories.options.physicalEnvironment.description',
    order: 8,
    subcategories: [
      {
        id: 'physical-environment-g9h8i7j6-productive-workspace-k1l2m3n4',
        name: 'Creating a productive and inspiring workspace',
        instruction: 'Tips for designing an efficient and motivating work environment',
        image: '',
        translateKey: 'Categories.options.physicalEnvironment.creatingAProductiveAndInspiringWorkspace',
      },
      {
        id: 'physical-environment-g9h8i7j6-household-chores-o5p6q7r8',
        name: 'Managing household responsibilities and chores',
        instruction: 'Strategies for effectively handling domestic tasks and duties',
        image: '',
        translateKey: 'Categories.options.physicalEnvironment.managingHouseholdResponsibilitiesAndChores',
      },
      {
        id: 'physical-environment-g9h8i7j6-comfortable-living-s9t8u7v6',
        name: 'Finding and creating a comfortable living space',
        instruction: 'Guidance on establishing a cozy and personalized home environment',
        image: '',
        translateKey: 'Categories.options.physicalEnvironment.findingAndCreatingAComfortableLivingSpace',
      },
      {
        id: 'physical-environment-g9h8i7j6-declutter-home-w1x2y3z4',
        name: 'Organizing and decluttering home environments',
        instruction: 'Techniques for maintaining an orderly and clutter-free living space',
        image: '',
        translateKey: 'Categories.options.physicalEnvironment.organizingAndDeclutteringHomeEnvironments',
      },
    ],
  },
];